#!/bin/bash

if [ "$EUID" -ne 0 ]; then
	printf "\x1b[38;5;196mThis script must be run as root. Exiting...\x1b[39m\n"
	exit 1
fi

run() {
	exec=$1
	printf "\x1b[38;5;104m --> ${exec}\x1b[39m\n"
	eval ${exec}
}

say() {
	say=$1
	printf "\x1b[38;5;220m${say}\x1b[38;5;255m\n"
}

if [ "$EUID" -ne 0 ]; then
	say "Please run as root"
	exit
fi

MYPATH=${PWD}

say "Installing/Compiling SVXLink"
run "git clone https://github.com/sm0svx/svxlink.git"

cd /tmp

say "Installing svxlink sounds"
run "cd /usr/share/svxlink/sounds"
run 'git clone "https://github.com/sm0svx/svxlink-sounds-en_US-heather"'
run "${MYPATH}/svxlink/src/svxlink/scripts/filter_sounds.sh -r 16000 svxlink-sounds-en_US-heather en_US"
run "rm -fr svxlink-sounds-en_US-heather"
run "rm -f svxlink-sounds-en_US.tar.bz2"

cd ${MYPATH}
rm -fr svxlink
