#!/bin/bash

if [ "$EUID" -ne 0 ]; then
	printf "\x1b[38;5;196mThis script must be run as root. Exiting...\x1b[39m\n"
	exit 1
fi

run() {
	exec=$1
	printf "\x1b[38;5;104m --> ${exec}\x1b[39m\n"
	eval ${exec}
}

say() {
	say=$1
	printf "\x1b[38;5;220m${say}\x1b[38;5;255m\n"
}

say "Updateing WM8960 audio interface"
# test audio files https://www2.cs.uic.edu/~i101/SoundFiles/
cd /tmp
run "git clone https://github.com/waveshare/WM8960-Audio-HAT"
cd WM8960-Audio-HAT/
run "./install.sh"
cd -
